from setuptools import setup, find_packages

setup(
    name="acb_db",
    version="0.1",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
            "attrs==24.3.0",
            "beautifulsoup4==4.12.3",
            "bs4==0.0.2",
            "certifi==2024.12.14",
            "cffi==1.17.1",
            "charset-normalizer==3.4.1",
            "contourpy==1.3.1",
            "cycler==0.12.1",
            "exceptiongroup==1.2.2",
            "fonttools==4.55.3",
            "h11==0.14.0",
            "idna==3.10",
            "kiwisolver==1.4.8",
            "matplotlib==3.10.0",
            "numpy==2.2.1",
            "outcome==1.3.0.post0",
            "packaging==24.2",
            "pandas==2.2.3",
            "pillow==11.1.0",
            "psycopg2==2.9.10",
            "pycparser==2.22",
            "pyparsing==3.2.1",
            "PySocks==1.7.1",
            "python-dateutil==2.9.0.post0",
            "python-dotenv==1.0.1",
            "pytz==2024.2",
            "regex==2024.11.6",
            "requests==2.32.3",
            "selenium==4.27.1",
            "setuptools==75.6.0",
            "six==1.17.0",
            "sniffio==1.3.1",
            "sortedcontainers==2.4.0",
            "soupsieve==2.6",
            "trio==0.28.0",
            "trio-websocket==0.11.1",
            "typing_extensions==4.12.2",
            "tzdata==2024.2",
            "urllib3==2.3.0",
            "websocket-client==1.8.0",
            "wsproto==1.2.0"
        ],
    author="Pablo De Marcos Cortón",
    author_email="pablodmc27@gmail.com",
    description="Package to create and update a database of the ACB basketball league through scraping of official ACB pages",
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url="https://github.com/PabloDMC/ACB_DB",
    classifiers=[
        "Programming Language :: Python :: 3.10",
        "License :: OSI Approved :: MIT License",
        "Operating System :: Microsoft :: Windows",
    ],
    python_requires='>=3.10',
)